# Generated by Django 4.1.2 on 2023-08-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="craete_date",
            new_name="create_date",
        ),
    ]
